name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: PWA to Android APK
        uses: pwabuilder/pwa-action@v1
        with:
          manifest-url: 'https://fox1pocket.github.io/foxpocket/manifest.json'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FoxPocket-APK
          path: ./*.apk
          
