name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build APK
      run: |
        npm install -g @bubblewrap/cli
        npx @bubblewrap/cli init --manifest=https://fox1pocket.github.io/foxpocket/manifest.json --directory=./
        npx @bubblewrap/cli build

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: FoxPocket-APK
        path: ./*.apk
        
